educa/QuizApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('home.urls')),


]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educa/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
     path('room/<int:course_id>/', views.course_chat_room,
             name='course_chat_room'),
]

educa/educa/urls.py
# from django.conf.urls import include, url
# from django.contrib import admin
# from django.contrib.auth import views as auth_views
#
# from django.conf import settings
# from django.conf.urls.static import static
# from courses.views import CourseListView
# from django.urls import path, include
#
#
# urlpatterns = [
#     path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
#     path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
#     path('admin/', admin.site.urls),
#     path('course/', include('courses.urls')),
#     url(r'^students/', include('students.urls')),
#     url(r'^$', CourseListView.as_view(), name='course_list'),
# ]
#
# urlpatterns += static(settings.MEDIA_URL,
#                       document_root=settings.MEDIA_ROOT)
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from courses.views import CourseListView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static






urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(),  name='course_list'),
    path('students/', include('students.urls')),
    # path('home/', include('home.urls', namespace='home')),
    path("home/", include('home.urls')),
    path("QuizApp/", include('QuizApp.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    # url(r'^$', CourseListView.as_view(), name='courses/templates/course/list.html'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educa/students/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('register/',
             views.StudentRegistrationView.as_view(),
             name='student_registration'),
    path('enroll-course/',
             views.StudentEnrollCourseView.as_view(),
             name='student_enroll_course'),
    path('courses/',
             views.StudentCourseListView.as_view(),
             name='student_course_list'),
    path('course/<pk>/',
             views.StudentCourseDetailView.as_view(),
             name='student_course_detail'),
    path('course/<pk>/<module_id>/',
             views.StudentCourseDetailView.as_view(),
             name='student_course_detail_module'),
]

educa/students/models.py
from django.db import models

# Create your models here.

educa/students/forms.py
from django import forms
from courses.models import Course

class CourseEnrollForm(forms.Form):
     course = forms.ModelChoiceField(queryset=Course.objects.all(),
                                        widget=forms.HiddenInput)

educa/students/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CourseEnrollForm
from django.views.generic.list import ListView
from courses.models import Course
from django.views.generic.detail import DetailView

class StudentRegistrationView(CreateView):
     template_name = 'students/student/registration.html'
     form_class = UserCreationForm
     success_url = reverse_lazy('student_course_list')

     def form_valid(self, form):
         result = super(StudentRegistrationView, self).form_valid(form)
         cd = form.cleaned_data
         user = authenticate(username=cd['username'],
                                password=cd['password1'])
         login(self.request, user)
         return result

class StudentEnrollCourseView(LoginRequiredMixin, FormView):
     course = None
     form_class = CourseEnrollForm

     def form_valid(self, form):
         self.course = form.cleaned_data['course']
         self.course.students.add(self.request.user)
         return super(StudentEnrollCourseView, self).form_valid(form)

     def get_success_url(self):
         return reverse_lazy('student_course_detail', args=[self.course.id])

class StudentCourseListView(LoginRequiredMixin, ListView):
     model = Course
     template_name = 'students/course/list.html'

     def get_queryset(self):
         qs = super(StudentCourseListView, self).get_queryset()
         return qs.filter(students__in=[self.request.user])

class StudentCourseDetailView(DetailView):
    model = Course
    template_name = 'students/course/detail.html'

    def get_queryset(self):
        qs = super(StudentCourseDetailView, self).get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super(StudentCourseDetailView, self).get_context_data(**kwargs)
        # Получаем объект курса.
        course = self.get_object()
        if 'module_id' in self.kwargs:
            # Получаем текущий модуль по параметрам запроса.
            context['module'] = course.modules.get(id=self.kwargs['module_id'])
        else:
            # Получаем первый модуль.
            context['module'] = course.modules.all()[0]
        return context

educa/students/templates/students/course/detail.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}
    <h1>
        <center> {{ module.title }}</center>
    </h1>
    <div class="contents">
        <h3>Модулі</h3>
        <ul id="modules">
        {% for m in object.modules.all %}
            <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>
                <a href="{% url 'student_course_detail_module' object.id m.id %}">
                    <span>
                        Модуль <span class="order">{{ m.order|add:1 }}</span>
                    </span>
                    <br>
                    {{ m.title }}
                </a>
            </li>

        {% empty %}
            <li>Модулів поки немає.</li>
        {% endfor %}
        </ul>
        <h3>
             <a href="{% url 'chat:course_chat_room' object.id %}">
                Чат
             </a>
         </h3>
    </div>
    <div class="module">
   {% cache 600 module_contents module %}
        {% for content in module.contents.all %}
            {% with item=content.item %}
                <h2>{{ item.title }}</h2>
                {{ item.render|safe }}
            {% endwith %}
        {% endfor %}
    {% endcache %}

    </div>
{% endblock %}

educa/students/templates/students/course/list.html
{% extends "base.html" %}

{% block title %}Мої курси{% endblock %}

{% block content %}
     <h1>Мої курси </h1>

     <div class="module">

         {% for course in object_list %}
             <div class="course-info">
                 <h3>{{ course.title }}</h3>
                 <p><a href="{% url 'student_course_detail' course.id %}">
                 Переглянути вміст</a></p>
             </div>
         {% empty %}
             <p>
                 Ви ще не зареєстровані на жодних курсах.
                 <a href="{% url 'course_list' %}">Перегляд курсів</a>
                 записатися на курс.
             </p>
     {% endfor %}
     </div>
{% endblock %}